version: "3"
services:
  poller:
    build:
      ticker-poller/.
    volumes:
      - ./ticker-poller/code:/code
  mongodb:
    image: mongo:jessie
  api:
    build:
      ticker-api/.
    ports:
      - "8888:8080"
    volumes:
      - ./ticker-api/code:/code
